# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Util.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Util.proto',
  package='zeta_car',
  serialized_pb=_b('\n\nUtil.proto\x12\x08zeta_car\"0\n\x12IntIntKeyValuePair\x12\x0b\n\x03key\x18\x01 \x02(\x03\x12\r\n\x05value\x18\x02 \x02(\x03\x42\x1a\n\x16\x63om.zetast.carnet.utilP\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INTINTKEYVALUEPAIR = _descriptor.Descriptor(
  name='IntIntKeyValuePair',
  full_name='zeta_car.IntIntKeyValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='zeta_car.IntIntKeyValuePair.key', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='zeta_car.IntIntKeyValuePair.value', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['IntIntKeyValuePair'] = _INTINTKEYVALUEPAIR

IntIntKeyValuePair = _reflection.GeneratedProtocolMessageType('IntIntKeyValuePair', (_message.Message,), dict(
  DESCRIPTOR = _INTINTKEYVALUEPAIR,
  __module__ = 'Util_pb2'
  # @@protoc_insertion_point(class_scope:zeta_car.IntIntKeyValuePair)
  ))
_sym_db.RegisterMessage(IntIntKeyValuePair)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.zetast.carnet.utilP\001'))
# @@protoc_insertion_point(module_scope)
